name       : opencl-clhpp
version    : 2023.04.17
release    : 3
source     :
    - https://github.com/KhronosGroup/OpenCL-CLHPP/archive/refs/tags/v2023.04.17.tar.gz : 179243843c620ef6f78b52937aaaa0a742c6ff415f9aaefe3c20225ee283b357
license    : Apache-2.0
component  : programming.devel
homepage   : https://github.com/KhronosGroup/OpenCL-CLHPP/
summary    : OpenCL C++ header files
description: |
    OpenCL (Open Computing Language) header files for the C++ programming language.
patterns   :
    - /usr/include/CL/*
install    : |
    install -Dm00644 include/CL/*.hpp -t $installdir/usr/include/CL
