name       : opencl-clhpp
version    : 2.0.13
release    : 1
source     :
    - https://github.com/KhronosGroup/OpenCL-CLHPP/archive/refs/tags/v2.0.13.tar.gz : 8ff0d0cd94d728edd30c876db546bf13e370ee7863629b4b9b5e2ef8e130d23c
license    : Apache-2.0
component  : programming.devel
homepage   : https://github.com/KhronosGroup/OpenCL-CLHPP/
summary    : OpenCL C++ header files
description: |
    OpenCL (Open Computing Language) header files for the C++ programming language.
patterns   :
    - /usr/include/CL/*
install    : |
    install -Dm00644 include/CL/*.hpp -t $installdir/usr/include/CL
